import React from "react";
import Base from "./Base";
import "./TC.css";

function TC() {
  return (
    <Base>
      <div className="container">
        <div className="tc">
          <div className="card h-100">
            <div className="card-header">
              <h5>Terms and Condition</h5>
            </div>
            <div className="card-body">
              <ol className="lists">
                <li>
                  <b>General</b>
                  <p>
                    www.spectramedglobal.com is an internet portal and
                    “Spectramed” is the mobile application (henceforth in this
                    document, together both platforms may be labelled as
                    “Website” or “Mobile Application” or platforms of
                    “Spectramed Global Health Management LLP”) is hosted and
                    operated by Spectramed Global Health Management LLP
                    (hereafter referred to as “Company” or “Us” or “We” or
                    “Our”). Spectramed Global Health Management LLP is a Company
                    incorporated under the Limited Liability Partnership Act,
                    2008. <br />
                    The mailing address of this Company is: Off 101, 1st Floor,
                    Gokul Plaza, Next to Adani Payment Centre, Old Nagardas
                    Road, Andheri East. Mumbai 400069. Maharashtra. India.
                    <br />
                    For the purpose of ease of addressal, this document may term
                    the user as “You”. The user is any eligible person who
                    accepts our Terms and Conditions and agrees to register on
                    our Website by providing all the information required to
                    create a Vendor account. By accepting the Terms and
                    Conditions, you agree that the information provided by you
                    is accurate and there is no discrepancy on purpose on the
                    information provided by you. By clicking on “I Agree” to the
                    terms and conditions, we believe that you have gone through
                    this document thoroughly.
                  </p>
                </li>
                <li>
                  <b>Professional Standards</b>
                  <p>
                    Our products and services are rendered either from our own
                    licensed premises or from the licensed premises of our
                    associates / network pharmacies or diagnostic centers or
                    laboratories or any relevant institution depending on the
                    product or service requested by the user. The partnered
                    vendors by Spectramed are undertaken under strict
                    supervision of the qualified and registered pharmacists /
                    doctors / relevant qualified personnel. All the registered
                    vendors are bound by their corresponding codes of
                    professional ethics and conduct.{" "}
                  </p>
                </li>
                <li>
                  <b>Products and Services</b>
                  <p>
                    The Website is a stage that encourages online healthcare
                    services by the client for acquisition of medicines/
                    diagnostic services/ healthcare and wellness products or any
                    such related products offered by third party vendors
                    appointed by the Company. The dealing of sales/buy/exchange
                    between the enlisted third parties and you, of Products and
                    Services, is encouraged by the demand set by you on the
                    Website and the same will be administered by these Terms.
                    The Company isn't and can't be a party to or spare as aside
                    from as might be given in these Terms of Use, control in any
                    way, any exchange among you and the outsiders.{" "}
                  </p>
                  <ol type="A">
                    <li>Diagnostic Service</li>
                    <ul className="service">
                      <li id="nest">
                        The Company offers assistance through the Website as an
                        online marketplace and encourages the Users to profit
                        from the diagnostic tests offered by third party
                        laboratories through the Website.
                      </li>
                      <li id="nest">
                        Further, the Company will in no occasion be liable for
                        the samples collected for tests, processing of the
                        samples and the reports generated by the laboratories.
                        The Company just gives assistance for the booking of the
                        test with the various laboratories to the Users of the
                        Website.
                      </li>
                      <li id="nest">
                        By utilizing these services, you agree that the Client
                        and the Labs consent to utilize the Website and the
                        materials gave in that just to purposes that are allowed
                        by: (a) these Terms of Use; and (b) any appropriate
                        law(s), guideline or by and large acknowledged practices
                        or rules in the applicable wards.
                      </li>
                    </ul>
                  </ol>
                </li>
                <br />
                <li>
                  <b>Eligibility for Use</b>
                  <p>
                    The user must be of minimum 18 years of age to get
                    registered on our Website. The Products and Services on our
                    platform are not available for the user who were removed or
                    suspended from our platform for any reason whatsoever. The
                    Company also reserved to suspend and terminate the account
                    of any user if it is brought to our notice that the user is
                    under 18 years of age. Company shall allow you to use the
                    product and services on our Website only if the individual
                    agrees to share the required User Information, including
                    without limitation, name; user ID; email address; address;
                    gender; age; phone number; password; valid finance account
                    information; and other details and created an account
                    through Company ID and password.
                  </p>
                </li>
                <li>
                  <b>Registration</b>
                  <p>
                    You will not have more than one active registered account on
                    the Website. Also, you are denied from selling, exchanging,
                    or in any case moving your account to another party. The
                    Company maintains all authority to reject access to utilize
                    the services offered at the Website to new Users or to end
                    access conceded to existing Users whenever, without
                    concurring any explanations behind doing as such and you
                    will reserve no option to protest the equivalent.
                  </p>
                </li>
                <li>
                  <b>User Account,Password and Security</b>
                  <p>
                    The Website expects You to enlist as a User by making an
                    Account so as to yield the benefits of the products and
                    services offered by the Website. You will be responsible for
                    keeping up the privacy of the Account Information and are
                    completely liable for all exercises that happen under Your
                    Account. In case of any breach of security in your account,
                    it is your responsibility to notify us immediately. You
                    should logout of the account after every session to protect
                    your privacy. Company cannot and will not be liable for any
                    loss or damage in case of any failure from your side to
                    adhere to these basic compliances.
                  </p>
                </li>
                <li>
                  <b>Returns,Cancellations and Refunds</b>
                  <p>
                    Full refunds on cancellations of diagnostic orders is only
                    applicable if the cancellation requested is placed minimum 1
                    hour prior to the booking time. In case of the claim of full
                    refund for late cancellation request, the customer needs to
                    justify the reason over an email and the same will be
                    verified on case to case basis. Full refunds will only be
                    processed if the partner vendor agrees for the same. For
                    routine late cancellation cases, the customer will be
                    charged Rs. 50 apart from Payment Processing Charges
                    (wherever applicable.) In case the customer chose the mode
                    of payment as cash on delivery, this amount will be adjusted
                    from the wallet or from the future orders.
                    <br />
                    If the claim of refund or cancellation of the customer is
                    found to be valid, following will be the mode of refund:
                  </p>
                  <ol className="returns">
                    <li id="nest">
                      If the payment was made through Spectramed Wallet, the
                      money will be refunded back to the wallet within 15
                      business days.
                    </li>
                    <li id="nest">
                      If the payment was made through cash, online, UPI, debit
                      card or credit card, the money will be refunded back to
                      the wallet unless specified by the customer to be
                      transferred to a certain bank account. Bank payment
                      processing charges may be deducted in certain cases.
                    </li>
                  </ol>
                </li>
                <br />
                <li>
                  <b>Privacy Policy</b>
                  <p>
                    The Company further maintains all authority to change or
                    alter these Terms of Use or any strategy or rules of the
                    Website including the Privacy Policy, whenever and in its
                    sole discretion. Any progressions or alterations caused will
                    to be taking effect right away after posting the updates on
                    the Website and You excuse any right you may have to get
                    explicit notification of such changes or adjustments. Your
                    utilization of the Website will affirm your acknowledgment
                    of such changes or alterations.
                  </p>
                </li>
              </ol>
              <b className="dis_title">Disclaimer</b>
              <p className="dis_content">
                Spectramed Global Health Management LLP may alter these terms
                and conditions and some other records consolidated by reference
                thus at its sole decision for agreeing to the surviving lawful
                and administrative system and for other authentic business
                purposes, whenever, and Spectramed Global Health Management LLP
                will post the corrected terms of utilization, with or with no
                notice to you, on the various digital platforms hosted by
                Spectramed Global Health Management LLP. It is your duty to
                audit the terms and conditions for any progressions and you are
                urged to check the terms and conditions every now and again.
                Your utilization of the Spectramed Global Health Management LLP
                stage following any alteration of the terms and conditions will
                imply your consent to and acknowledgment of any amended terms
                and conditions. On the off chance that you don't consent to
                comply with these or any future terms and conditions, kindly
                don't utilize or access the Spectramed Global Health Management
                LLP platforms.
                <br />
                The transaction and collection of the Products by the registered
                merchants/vendors may also be subject to procedures for use of
                the Website, Terms, uploaded guidelines, rules, additional terms
                of service, or other disclaimer & notices, if any. If there is
                any conflict between the Terms and the Additional Terms, the
                Additional Terms shall take precedence in relation to that
                service.
              </p>
            </div>
          </div>
        </div>
      </div>
    </Base>
  );
}

export default TC;
